### ISSUE TITLE
Missing/Broken "3D Charts in Dash" code snippet

### ISSUE THREAD

**Issue by hristog** [plotly/graphing-library-docs#185]
The Dash [3d-scatter-plots](https://dash.gallery/python-docs-dash-snippets/3d-scatter-plots) snippet appears to be missing/broken. It is referenced from https://github.com/plotly/graphing-library-docs/blob/4195295ae2d3fe98db4a5353862e79f7b42e1acc/_posts/python/2019-07-03-3d-index.html#L46

This was originally spotted [here](https://plotly.com/python/3d-charts/).

**Comment by danton267** [comment]
Thank you for letting us know @hristog. The issue has been fixed.
