### ISSUE TITLE
Failed to fetch http://ftp.us.debian.org/debian/dists/jessie...

### ISSUE THREAD

**Issue by LiamConnors** [plotly/graphing-library-docs#230]
The tests to build the docs fail when fetching debian.
Looks like the required dist no longer exists at
http://ftp.us.debian.org/debian/dists/

**Comment by LiamConnors** [comment]
It seems it might be this issue reoccurring https://github.com/plotly/graphing-library-docs/pull/210

**Comment by archmoj** [comment]
Is this happening on the `master` branch?

**Comment by LiamConnors** [comment]
Yes, it would have affected main too. It's now resolved. https://github.com/plotly/graphing-library-docs/pull/231 Thanks!
