### ISSUE TITLE
Load fig

### ISSUE THREAD

**Issue by wesszabo** [plotly/graphing-library-docs#33]
[https://plot.ly/python/v3/slider-widget/#using-a-single-slider-to-set-the-range](url)

`fig = plotly.plotly.get_figure("https://plot.ly/~jordanpeterson/889")`

AttributeError: module 'plotly' has no attribute 'plotly'

`fig = plotly.get_figure("https://plot.ly/~jordanpeterson/889")`

AttributeError: module 'plotly' has no attribute 'get_figure'

**Comment by nicolaskruchten** [comment]
Please note that the page you've linked to is for version 3 of `plotly`... The error message you're seeing suggests that you're using version 4.

**Comment by wesszabo** [comment]
Ahh, omg, sorry.
