### ISSUE TITLE
the link is 404

### ISSUE THREAD

**Issue by sethu24** [plotly/graphing-library-docs#57]
https://plotly.com/python/embedding-plotly-graphs-in-HTML/

For more on embedding Plotly graphs in HTML documents, **see our tutorial.**

**Comment by jdamiba** [comment]
Thanks @sethu24 for pointing this out. I have updated that hyperlink so that it points to the relevant page - see https://github.com/plotly/graphing-library-docs/pull/59

**Comment by sethu24** [comment]
you are welcome
