### ISSUE TITLE
plotlyProxy 404 error

### ISSUE THREAD

**Issue by statasaurus** [plotly/graphing-library-docs#72]
There seems to be an error with the plotlyProxy example plot. This is what I see when I load the page: 
<img width="655" alt="Screenshot 2020-05-03 at 20 42 40" src="https://user-images.githubusercontent.com/55274484/80924064-e6745200-8d7e-11ea-96f1-2e0a8b5cdea0.png">

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! This is actually an old and unmaintained page, so I'll remove it from our docs now :)
