### ISSUE TITLE
Participate in #Hacktoberfest

### ISSUE THREAD

**Issue by mojoaxel** [plotly/graphing-library-docs#99]
Please consider participating in the [#Hacktoberfest](https://hacktoberfest.digitalocean.com/) 2020.

You can easily do this by adding a topic `hacktoberfest` to this repository in github. This could encourage people to fix bugs and provide pull-requests.

In addition you could create also a label `Hacktoberfest` and label "simple" issues that could/should be tackled by the community.

[Here is a video that shows how maintainer can opt-in to Hacktoberfest contributions](https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean)

Thanks!

**Comment by nicolaskruchten** [comment]
Thanks! We've tagged a few issues in plotly.js and plotly.py but there's not a lot of low-hanging fruit here in the docs repo IMO :)

**Comment by mojoaxel** [comment]
@nicolaskruchten Thanks! But for contributions to count sadly you also need to add a "topic" `hacktoberfest`. This will show up here:
![image](https://user-images.githubusercontent.com/600565/95237577-b1c26600-0808-11eb-8c55-412762522639.png)

**Comment by nicolaskruchten** [comment]
Ah, thanks for letting me know. I've enabled this topic in these two repos: https://github.com/plotly/plotly.py/ and https://github.com/plotly/plotly.js/ ... let's see if we get flooded with low-quality PRs or if we can actually engage the community in a meaningful way :)
